import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

const helveticaNowDisplay = localFont({
  src: [
    {
      path: "../public/fonts/HelveticaNowDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/HelveticaNowDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/HelveticaNowDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now-display",
  display: "swap",
});

const albra = localFont({
  src: [
    {
      path: "../public/fonts/Albra-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Albra-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Albra-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-albra",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${roboto.variable} ${helveticaNowDisplay.variable} ${albra.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
